# Generated by Django 3.1.5 on 2021-01-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='H & A Research', max_length=255),
        ),
    ]
